import { Incident, Responder, UserProfile, SafetyCheckin, IncidentUpdate } from '../types';

export const DEMO_USERS: Record<string, UserProfile> = {
  reporter: {
    uid: 'demo_reporter_01',
    email: 'student.reporter@campus.edu',
    displayName: 'Elena Vance (Campus Resident)',
    role: 'reporter',
  },
  responder: {
    uid: 'demo_responder_01',
    email: 'marcus.firstaid@campus.edu',
    displayName: 'Officer Marcus Cole',
    role: 'responder',
    responderSpecialty: 'first_aid',
    phone: '555-0192',
  },
  admin: {
    uid: 'demo_admin_01',
    email: 'director.dispatch@campus.edu',
    displayName: 'Commander Sarah Jenkins',
    role: 'admin',
  },
};

export const DEMO_RESPONDERS: Responder[] = [
  {
    id: 'resp_firstaid_01',
    userId: 'demo_responder_01',
    name: 'Officer Marcus Cole',
    type: 'first_aid',
    status: 'Available',
    currentZone: 'Library Block & Central Quad',
    contactRadio: 'TAC-Channel 2',
    skills: ['CPR Certified', 'AED Operator', 'Severe Bleed Kit', 'Triage'],
    isDemo: true,
  },
  {
    id: 'resp_sec_02',
    userId: 'demo_responder_02',
    name: 'Sergeant David Kim',
    type: 'security',
    status: 'Dispatched',
    currentZone: 'East Gate & Parking Deck',
    contactRadio: 'TAC-Channel 1',
    skills: ['De-escalation', 'Access Override', 'Crowd Management'],
    isDemo: true,
  },
  {
    id: 'resp_facility_03',
    userId: 'demo_responder_03',
    name: 'Jordan Rivera',
    type: 'facility',
    status: 'Available',
    currentZone: 'Engineering Science Quad',
    contactRadio: 'OPS-Channel 4',
    skills: ['Hazardous Containment', 'Utility Isolation', 'Elevator Extrication'],
    isDemo: true,
  },
];

export const DEMO_INCIDENTS: Incident[] = [
  {
    id: 'INC-2026-0881',
    reporterId: 'demo_reporter_01',
    reporterName: 'Anonymous Student',
    reporterAnonymous: true,
    category: 'medical',
    description: 'A student fainted on the 2nd floor study mezzanine near the east quiet carrels. Pale, shallow breathing, conscious but unresponsive to questions.',
    locationName: 'W.T. Young Library Block, 2nd Floor Mezzanine',
    zone: 'Library Block',
    mapCoordinates: { x: 48, y: 38 },
    imageUrl: '',
    status: 'Verified',
    urgency: 'High',
    originalAiUrgency: 'High',
    urgencyOverridden: false,
    adminNotes: 'Sample high-priority medical incident near Library Block. First-aid team alerted.',
    aiAnalysis: {
      category: 'medical',
      urgency: 'High',
      confidence: 0.94,
      approximateLocation: 'Library Block (Near 2nd Floor Mezzanine)',
      missingInformation: ['Exact staircase or elevator closest to the student', 'Whether bystander CPR or AED has been fetched'],
      explanation: 'Unresponsive fainting event with shallow breathing qualifies as urgent non-trauma medical emergency requiring rapid first-aid triage.',
      disclaimer: 'AI RECOMMENDATION ONLY. This analysis is an algorithmic prioritization suggestion and NOT a medical diagnosis, dispatch order, or emergency authority decision.',
      analyzedAt: '2026-09-18T22:45:00Z',
    },
    assignedResponderId: 'resp_firstaid_01',
    assignedResponderName: 'Officer Marcus Cole (First-Aid)',
    createdAt: '2026-09-18T22:42:00Z',
    updatedAt: '2026-09-18T22:50:00Z',
    isDemo: true,
  },
  {
    id: 'INC-2026-0879',
    reporterId: 'demo_reporter_02',
    reporterName: 'Residential Advisor',
    reporterAnonymous: false,
    category: 'security',
    description: 'Exterior fire exit door prop alarm sounding continuously at South Tower Residence. Unidentified individual seen lingering by bike racks.',
    locationName: 'South Tower Residence Hall, Wing B',
    zone: 'South Residential Quad',
    mapCoordinates: { x: 74, y: 68 },
    status: 'Responding',
    urgency: 'Medium',
    originalAiUrgency: 'Medium',
    urgencyOverridden: false,
    adminNotes: 'Assigned to Security Team. Responder on foot patrol.',
    aiAnalysis: {
      category: 'security',
      urgency: 'Medium',
      confidence: 0.89,
      approximateLocation: 'South Residential Quad (Wing B Exit)',
      missingInformation: ['Physical direction individual walked', 'Whether door latch is physically damaged'],
      explanation: 'Building perimeter violation with lingering party. Moderate priority for on-duty security verification.',
      disclaimer: 'AI RECOMMENDATION ONLY. This analysis is an algorithmic prioritization suggestion and NOT a medical diagnosis, dispatch order, or emergency authority decision.',
      analyzedAt: '2026-09-18T22:10:00Z',
    },
    assignedResponderId: 'resp_sec_02',
    assignedResponderName: 'Sergeant David Kim (Security)',
    createdAt: '2026-09-18T22:05:00Z',
    updatedAt: '2026-09-18T22:25:00Z',
    isDemo: true,
  },
  {
    id: 'INC-2026-0875',
    reporterId: 'demo_reporter_03',
    reporterName: 'Facility Monitor',
    reporterAnonymous: false,
    category: 'facility',
    description: 'High-pressure water valve dripping rapidly onto electrical conduits in basement corridor near chemical storage.',
    locationName: 'Chemistry Hall North, Sub-level 1',
    zone: 'Science Quad',
    mapCoordinates: { x: 26, y: 55 },
    status: 'Resolved',
    urgency: 'Medium',
    originalAiUrgency: 'High',
    urgencyOverridden: true,
    adminNotes: 'Facility supervisor shut main riser. Water vacuumed. Certified safe.',
    aiAnalysis: {
      category: 'facility',
      urgency: 'High',
      confidence: 0.91,
      approximateLocation: 'Science Quad (Chemistry Hall Basement)',
      missingInformation: ['Distance from dripping valve to electrical junction box'],
      explanation: 'Water proximity to electrical conduit presents electrocution or short-circuit hazard.',
      disclaimer: 'AI RECOMMENDATION ONLY. This analysis is an algorithmic prioritization suggestion and NOT a medical diagnosis, dispatch order, or emergency authority decision.',
      analyzedAt: '2026-09-18T20:15:00Z',
    },
    assignedResponderId: 'resp_facility_03',
    assignedResponderName: 'Jordan Rivera (Facility)',
    createdAt: '2026-09-18T20:10:00Z',
    updatedAt: '2026-09-18T21:30:00Z',
    isDemo: true,
  },
];

export const DEMO_UPDATES: IncidentUpdate[] = [
  {
    id: 'upd_01',
    incidentId: 'INC-2026-0881',
    actorId: 'system',
    actorRole: 'system',
    actorName: 'ResQRoute Intake AI',
    statusFrom: 'Reported',
    statusTo: 'Under review',
    message: 'Report logged. Automated safety triage executed (Urgency: High). Dispatched to Admin Command Center.',
    timestamp: '2026-09-18T22:43:00Z',
  },
  {
    id: 'upd_02',
    incidentId: 'INC-2026-0881',
    actorId: 'demo_admin_01',
    actorRole: 'admin',
    actorName: 'Commander Sarah Jenkins',
    statusFrom: 'Under review',
    statusTo: 'Verified',
    message: 'Report verified via CCTV mezzanine camera. Assigned Officer Marcus Cole (First-Aid squad).',
    timestamp: '2026-09-18T22:46:00Z',
  },
  {
    id: 'upd_03',
    incidentId: 'INC-2026-0881',
    actorId: 'resp_firstaid_01',
    actorRole: 'responder',
    actorName: 'Officer Marcus Cole',
    statusFrom: 'Verified',
    statusTo: 'Assigned',
    message: 'Assignment accepted. Moving with portable AED and trauma jump kit.',
    timestamp: '2026-09-18T22:48:00Z',
  },
];

export const DEMO_SAFETY_CHECKINS: SafetyCheckin[] = [
  {
    id: 'chk_01',
    zone: 'Library Block',
    status: 'safe',
    note: 'Safe on 4th floor reading room',
    timestamp: '2026-09-18T22:52:00Z',
    isDemo: true,
    isPublic: true,
  },
  {
    id: 'chk_02',
    zone: 'South Residential Quad',
    status: 'safe',
    note: 'All good in Dorm B common lounge',
    timestamp: '2026-09-18T22:50:00Z',
    isDemo: true,
    isPublic: true,
  },
  {
    id: 'chk_03',
    zone: 'Science Quad',
    status: 'safe',
    timestamp: '2026-09-18T22:45:00Z',
    isDemo: true,
    isPublic: true,
  },
  {
    id: 'chk_04',
    zone: 'Student Center & Dining',
    status: 'safe',
    note: 'Large group present, calm',
    timestamp: '2026-09-18T22:40:00Z',
    isDemo: true,
    isPublic: true,
  },
];

export const CAMPUS_ZONES = [
  'Library Block',
  'South Residential Quad',
  'Science & Engineering Quad',
  'Student Center & Dining Plaza',
  'Athletics & Recreation Complex',
  'North Parking & Transit Deck',
  'Administration & Health Services',
];
